spring:
  datasource:
    url: jdbc:mysql://localhost:3306/RestApiDemo
    username: root
    password: Thuong191020
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        #spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
      # option :  none / validate / create / create-drop / update
      # if not config this jpa.hibernate the default is : create-drop
      ddl-auto : validate
    # show log database for debug
    show-sql : true